
CREATE TABLE IF NOT EXISTS "Usuario" (
	"id_usuario" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"nome" VARCHAR(100),
	"email" VARCHAR(100),
	"telefone" VARCHAR(20),
	"senha" VARCHAR(255),
	PRIMARY KEY("id_usuario")
);




CREATE TABLE IF NOT EXISTS "Pontos" (
	"id_ponto" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"fk_id_usuario" INTEGER,
	"quantidade" INTEGER,
	"data_registro" DATE,
	PRIMARY KEY("id_ponto")
);




CREATE TABLE IF NOT EXISTS "Produto" (
	"id_produto" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"Nome" VARCHAR(100),
	"Descricao" VARCHAR(100),
	"Data_Registro" DATE,
	PRIMARY KEY("id_produto")
);



ALTER TABLE "Pontos"
ADD FOREIGN KEY("fk_id_usuario") REFERENCES "Usuario"("id_usuario")
ON UPDATE NO ACTION ON DELETE NO ACTION;